import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import { Toaster } from "@/components/ui/toaster";
import "./globals.css";
import ReduxWrapper from "@/redux/ReduxWrapper";

export const metadata: Metadata = {
  title: "Stay Manager",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="dark:bg-gray-900 bg-white duration-700">
        <ReduxWrapper>
          <main>{children}</main>
        </ReduxWrapper>
        <Toaster />
      </body>
    </html>
  );
}
